# ==============================================
# Configurações da aplicação
# ==============================================
spring.application.name=gerenciamento-tarefas

# ==============================================
# Configuração do MongoDB
# ==============================================
spring.data.mongodb.uri=mongodb://localhost:27017/gerenciamento_tarefas

# ==============================================
# Configuração do servidor
# ==============================================
server.port=8080

# ==============================================
# Configurações opcionais de logging
# ==============================================
logging.level.org.springframework=INFO
logging.level.com.renata.gerenciamentotarefas=DEBUG

