# ==============================================
# Configura��es da aplica��o
# ==============================================
spring.application.name=gerenciamento-tarefas

# ==============================================
# Configura��o do MongoDB
# ==============================================
spring.data.mongodb.uri=mongodb://localhost:27017/gerenciamento_tarefas

# ==============================================
# Configura��o do servidor
# ==============================================
server.port=8080

# ==============================================
# Configura��es opcionais de logging
# ==============================================
logging.level.org.springframework=INFO
logging.level.com.renata.gerenciamentotarefas=DEBUG

